apiVersion: v1
kind: Service
metadata:
  labels:
    app: znc
    tier: relay
  name: znc
spec:
  ports:
  - port: 6697
    protocol: TCP
    targetPort: irc
    name: irc
  selector:
    app: znc
    tier: relay
  type: LoadBalancer
