apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: znc
    tier: relay
  name: znc
spec:
  replicas: 1
  selector:
    app: znc
    tier: relay
  template:
    metadata:
      labels:
        app: znc
        tier: relay
    spec:
      volumes:
      - name: data
        gcePersistentDisk:
          pdName: znc
          fsType: ext4
      containers:
      - image: paralin/znc:latest
        imagePullPolicy: Always
        name: znc
        volumeMounts:
        - name: data
          mountPath: /znc-data
        ports:
        - containerPort: 6697
          protocol: TCP
          name: irc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
